source 'https://rubygems.org'

ruby '3.4.1'
gem 'sinatra'
gem 'rackup'
gem 'puma'
gem 'telegram-bot-ruby'
gem 'dotenv'
gem 'logger'
gem 'json'
gem 'rack-protection'
gem 'activerecord'
gem 'pg'
gem 'sinatra-activerecord'
gem 'rake'